### ISSUE TITLE
fconf 3g-ras --disable not deleting wvdial config

### ISSUE THREAD

**Issue by miopa** [FarmRadioHangar/fconf#14]
It's impossible to --enable after this, as it detects the wvdial file. 

Which makes me think that updating config and running --enable will fail too ..

**Comment by gernest** [comment]
@miopa so what are you proposing? we leave the file after disable?

config should work, since the file will be created.

**Comment by miopa** [comment]
I'm not sure I'm following you. If the file is created on --config, then you can overwrite it when configuring other dongle.

Correct behavior should be:
on `--disable` delete the wvdial config
on `--enable` create the wvdial config if no other data dongle is enabled

**Comment by gernest** [comment]
@miopa sorry, but that is exactly what the current implementation is doing

**Comment by miopa** [comment]
You tested and you can confirm that the issue i opened is not happening?

On Feb 9, 2017 5:40 PM, "Geofrey Ernest" <notifications@github.com> wrote:

@miopa <https://github.com/miopa> sorry, but that is exactly what the
current implementation is doing

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/FarmRadioHangar/fconf/issues/14#issuecomment-278660357>,
or mute the thread
